version: '3.8'
services:
  postgres:
    image: postgres:14
    ports:
      - '5435:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tec-medusa
    volumes:
      - ./docker_data/postgres:/var/lib/postgresql/data
      - ./docker_data/postgres_sql:/home/postgres_sql
